In [1]:
import copy,math
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)

In [7]:
x_train=np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
y_train=np.array([460,232,178])

In [8]:
x_train.shape

(3, 4)

In [9]:
y_train.shape

(3,)

In [10]:
print(x_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]


In [11]:
print(y_train)

[460 232 178]


In [12]:
b_init=785.1811367994083
w_init=np.array([0.39133535,18.75376741,-53.36032453,-26.42131618])

In [13]:
print(w_init)

[  0.39  18.75 -53.36 -26.42]


In [14]:
w_init.shape

(4,)

In [15]:
type(b_init)

float

In [16]:
def predict_single_loop(x,w,b):
    n=x.shape[0]
    p=0
    for i in range(n):
        p_i=x[i]*w[i]
        p=p+p_i
    p=p+b
    return p

In [17]:
print(x_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]


In [34]:
x_vec=x_train[0,:]
print(x_vec)

[2104    5    1   45]


In [35]:
x_train.shape

(3, 4)

In [36]:
x_vec.shape

(4,)

In [37]:
f_wb=predict_single_loop(x_vec,w_init,b_init)
print(f_wb)

459.9999976194083


In [39]:
def predict(x,w,b):
    p=np.dot(x,w)+b
    return p

In [40]:
print(x_vec)

[2104    5    1   45]


In [41]:
f_wb=predict(x_vec,w_init,b_init)

In [42]:
print(f_wb)

459.9999976194083


In [43]:
def compute_cost(x,y,w,b):
    m=x.shape[0]
    cost=0.0
    for i in range(m):
        f_wb_i=np.dot(x[i],w)+b
        cost=cost+(f_wb_i-y[i])**2
    cost=cost/(2*m)
    return cost

In [44]:
cost=compute_cost(x_train,y_train,w_init,b_init)

In [45]:
print(cost)

1.5578904045996674e-12


In [46]:
def compute_gradient(X,y,w,b):
    m,n=X.shape
    dj_dw=np.zeros((n,))
    dj_db=0.
    
    for i in range(m):
        err=(np.dot(X[i],w)+b)-y[i]
        for j in range(n):
            dj_dw[j]=dj_dw[j]+err*X[i,j]
        dj_db=dj_db+err
    dj_dw=dj_dw/m
    dj_db=dj_db/m
    
    return dj_db,dj_dw
    

In [47]:
tmp_dj_db,tmp_dj_dw=compute_gradient(x_train,y_train,w_init,b_init)
print(tmp_dj_db)
print(tmp_dj_dw)

-1.6739251122999121e-06
[-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05]


In [51]:
def gradient_descent(X,y,w_in,b_in,cost_function,gradient_function,alpha,num_iters):
    J_history=[]
    w=copy.deepcopy(w_in)
    b=b_in
    
    for i in range(num_iters):
        dj_db,dj_dw=gradient_function(X,y,w,b)
        w=w-alpha*dj_dw
        b=b-alpha*dj_db
        if i<100000:
            J_history.append(cost_function(X,y,w,b))
            
        if 1% math.ceil(num_iters/10)==0:
            print(f"iteration {i} cost is {J_history[i]}")
    return w,b,J_history

In [52]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.
# some gradient descent settings
iterations = 1000
alpha = 5.0e-7
# run gradient descent 
w_final, b_final, J_hist = gradient_descent(x_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient, 
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = x_train.shape
for i in range(m):
    print(f"prediction: {np.dot(x_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

b,w found by gradient descent: -0.00,[ 0.2   0.   -0.01 -0.07] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
